const chapters = [
  { id: 'chapter8', title: 'Chapter 8', words: ['accumulate','bare','castle','decorate','wound','charity','geography','heal','cell','disagree','nerve','option','passive','razor','scrape','vacant','vary','scholarship','accurate','category','deed','electronic','fasten','impact','paste','react','scratch','tense','mass','barely'], meanings: ['축적하다, 쌓이다','벌거벗은, 헐벗은','성','장식하다, 꾸미다','상처, 상처를 입히다','자선, 자선 단체','지리학, 지리, 지형','치료되다, 치유하다','세포, 감방, 독방','동의하지 않다','신경, 긴장, 불안','선택권','수동적인','면도칼','긁다, 긁어내다','비어 있는, 텅 빈','다르다, 변화를 주다','장학금','정확한','범주, 종류','행위, 행동','전자의','매다, 매이다','영향, 충돌, 충격','반죽, 풀, 풀로 붙이다','반응하다','긁다, 할퀴다, 긁힌 자국','팽팽한, 긴장한, 시제','덩어리, 무리, 질량, 대규모의','간신히, 겨우, 거의 ~않다'] },
  { id: 'chapter9', title: 'Chapter 9', words: ['accustomed','bargain','bandit','defeat','element','fate','impatient','lean','massive','path','realistic','scream','tension','caution','immigrate','defend','thorn','frame','recall','screw','terrific','grave','cemetery','scold','postpone','seaside','paw','recipe','vast','yield'], meanings: ['익숙한','싼 물건, 흥정하다','도적, 강도','패배시키다, 패배','요소, 성분','운명','참을성 없는','기대다','거대한, 대규모의','길, 산책길','현실적인','비명을 지르다, 비명','긴장, 팽팽함','조심, 주의, 경고','이주하다, 이주시키다','방어하다','가시','틀, 액자, 뼈대, 구조','상기하다, 기억해 내다, 회수하다','나사(못), 나사로 죄다','아주 좋은, 훌륭한','무덤, 산소','공동묘지','꾸짖다','연기하다, 미루다','해변, 바닷가','(동물의) 발','조리법','광대한','수확량, 수익률, 생산하다, 산출하다, (이익을) 내다'] },
];
const $ = selector => document.querySelector(selector);
const els = { setup: $('#setup-view'), list: $('#list-view'), options: $('#chapter-options'), start: $('#start'), eyebrow: $('#list-eyebrow'), words: $('#word-list'), again: $('#again') };
const shuffle = values => [...values].sort(() => Math.random() - .5);
function renderChapters() { els.options.innerHTML = chapters.map((chapter, index) => `<label><input type="radio" name="chapter" value="${chapter.id}" ${index === 0 ? 'checked' : ''} /><span>${chapter.title}</span><small>단어 ${chapter.words.length}개</small></label>`).join(''); }
function showList() { const chapter = chapters.find(item => item.id === $('input[name="chapter"]:checked').value); const mode = $('input[name="mode"]:checked').value; const entries = shuffle(chapter.words.map((word, index) => ({ word, meaning: chapter.meanings[index] }))); els.eyebrow.textContent = `${chapter.title.toUpperCase()} · ${entries.length} WORDS`; els.words.innerHTML = entries.map((entry, index) => { const isKorean = mode === 'korean' || (mode === 'mixed' && index >= 15); const label = isKorean ? entry.meaning : entry.word; return `<div class="word-row"><span class="word-number">${String(index + 1).padStart(2, '0')}</span><b>${label}</b></div>`; }).join(''); els.setup.hidden = true; els.list.hidden = false; }
els.start.addEventListener('click', showList); els.again.addEventListener('click', () => { els.list.hidden = true; els.setup.hidden = false; }); renderChapters();
